In [1]:
import numpy as np

In [5]:
A = np.array([[3,-9],[2,4]])

In [7]:
print(A)

[[ 3 -9]
 [ 2  4]]


In [10]:
B= np.array([-42,2])

In [16]:
Z=np.linalg.solve(A,B)

In [18]:
print(Z)

[-5.  3.]


In [20]:
M=np.array([[1,-2,-1],[2,2,-1],[-1,-1,2]])

In [22]:
print(M)

[[ 1 -2 -1]
 [ 2  2 -1]
 [-1 -1  2]]


In [24]:
c=np.array([6,1,1])

In [26]:
y=np.linalg.solve(M,c)

In [28]:
print(y)

[ 3. -2.  1.]
